### PR TITLE
Added views export command.

### PR DESCRIPTION
**Pull request by baizmandesign**
Hi there,

I've been in contact with Juan de Paco about adding export and import commands for views. This is my attempt to add the export portion. Can someone review the pull request and let me know if it needs any revision?

Thanks!

Saul

### CODE REVIEW

**Comment by zaantar** [comment]
Hello Saul, thank you very much for your contribution! At first sight, it looks good, the only missing thing is documentation (starting [here](https://github.com/OnTheGoSystems/toolset-cli/blob/master/docs/views.md)), but I can take care of that for you if it's too much of a hassle. We should be able to merge this in the coming days.

**Comment by baizmandesign** [comment]
@zaantar Thanks for your feedback. There are a couple comments in the code that I'd like to clean up, but I'll submit that as a PR at a later date.

Regarding documentation, I totally forgot to edit the corresponding Markdown file and will do so shortly. It will include documentation for both import and export, so the forthcoming PR with these changes should be merged after #2 and #3 are merged.

**Comment by zaantar** [comment]
Thank you for the fast response, @baizmandesign!

FYI, for now, we're still in a transition phase from our internal workflow & repository to GitHub, so I need to run this through the code review of our team, perhaps polish this a little, and I will probably merge all three PRs into one branch. In any case, I will update here once it's done.

**Comment by baizmandesign** [comment]
@zaantar That sounds good. All three commits should really be squashed into a single commit. Note that if you try to merge #2 and #3 in sequence, there may be a conflict in `application/Bootstrap.php` around line 30 (where the new commands are specified, since the same line number is edited).

There's something else I'd like to add to the import / export commands. Right now, the commands only work with XML, and I'd like to support zipped XML files, too (which is what the web interface supports). Would it be appropriate to open an issue for this?

Also, would it be possible to receive any public credit for these contributions, such as a mention in `README.md`?

Thanks!

**Comment by zaantar** [comment]
@baizmandesign the conflict is not a problem, meanwhile I also merged another [set of changes](https://github.com/OnTheGoSystems/toolset-cli/commit/1fde0910fd4e713079cfe944a0dcf41195550a77) and this is the least of my worries ;) 

A ZIP import/export support would be great! I'd suggest waiting until these three PRs are handled (should be a matter of a couple of days, at most) and only then start working on it (if you plan to do it yourself). In any case, yes, please do create the issue for tracking this effort. I'll gladly mention you in the readme, of course!

**Comment by baizmandesign** [comment]
Thanks, @zaantar! I've opened an issue and will wait for the existing changes to be merged prior to adding ZIP format support. :-)

**Comment by zaantar** [comment]
@baizmandesign the changes are merged (manually), feel free to continue :)

**Comment by baizmandesign** [comment]
Thanks for all of your help, @zaantar!

**Pull request closed without merging**
