### PR TITLE
Added documentation for views import and export commands.

### PR DESCRIPTION
**Pull request by baizmandesign**
@zaantar Per our correspondence, here is the documentation for the views import and export commands. Please merge this after merging #2 and #3. Thanks!

### CODE REVIEW

**Comment by zaantar** [comment]
Merged manually. Thank you for your contributions @baizmandesign!

**Comment by baizmandesign** [comment]
You're welcome, @zaantar! I'd love to be credited at some point in the docs, if possible. :-)

**Comment by zaantar** [comment]
@baizmandesign done, thanks for the reminder!

**Comment by baizmandesign** [comment]
Thanks, @zaantar! I appreciate it!

**Pull request closed without merging**
